version: '3'
services:
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:root@mysql:3306
    ports:
      - "3306:3306"
    volumes:
      - mysql-db-store:/var/lib/mysql
  

  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app_name
    ports:
      - "3000:3000"
    links:
      - db
  
volumes:
  mysql-db-store:
